'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("lopstaControlDATEINAME.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Hauptakte (EA)&lt;/label&gt;
        '''    &lt;value&gt;EA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Sonderheft (SH)&lt;/label&gt;
        '''    &lt;value&gt;SH&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Sonderakte (SA)&lt;/label&gt;
        '''    &lt;value&gt;SA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Beweismittelordner (BMO)&lt;/label&gt;
        '''    &lt;value&gt;BMO&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Fallakte (FA)&lt;/label&gt;
        '''    &lt;value&gt;FA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Spurenakte (SPA)&lt;/label&gt;
        '''    &lt;valu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property AkteBezeichnungen() As String
            Get
                Return ResourceManager.GetString("AkteBezeichnungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Schreiben&lt;/label&gt;
        '''    &lt;value&gt;Schreiben&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Antrag&lt;/label&gt;
        '''    &lt;value&gt;Antrag&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Stellungnahme&lt;/label&gt;
        '''    &lt;value&gt;Stellungnahme&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Verteidigungsschrift&lt;/label&gt;
        '''    &lt;value&gt;Verteidigungsschrift&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Gegenvorstellung&lt;/label&gt;
        '''    &lt;value&gt;Gegenvorstellung&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property BeaBezeichnungen() As String
            Get
                Return ResourceManager.GetString("BeaBezeichnungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandant&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandantin&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Geschädigter&lt;/label&gt;
        '''    &lt;value&gt;Gesch&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Geschädigte&lt;/label&gt;
        '''    &lt;value&gt;Gesch&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Rechtsanwalt&lt;/label&gt;
        '''    &lt;value&gt;RA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Polizei&lt;/label&gt;
        '''    &lt;value&gt;Pol&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;ite [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property BeaEmpfaenger() As String
            Get
                Return ResourceManager.GetString("BeaEmpfaenger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Schreiben&lt;/label&gt;
        '''    &lt;value&gt;Schreiben&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Email&lt;/label&gt;
        '''    &lt;value&gt;Email&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Fax&lt;/label&gt;
        '''    &lt;value&gt;Fax&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;beA&lt;/label&gt;
        '''    &lt;value&gt;beA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Antrag&lt;/label&gt;
        '''    &lt;value&gt;Antrag&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Verteidigungsschrift&lt;/label&gt;
        '''    &lt;value&gt;VertSchr&lt;/value&gt;
        '''  &lt;/item&gt;
        '''&lt;/lis [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property DateinameBezeichnungen() As String
            Get
                Return ResourceManager.GetString("DateinameBezeichnungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandant&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandantin&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Geschädigter&lt;/label&gt;
        '''    &lt;value&gt;Gesch&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Geschädigte&lt;/label&gt;
        '''    &lt;value&gt;Gesch&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Rechtsanwalt&lt;/label&gt;
        '''    &lt;value&gt;RA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Polizei&lt;/label&gt;
        '''    &lt;value&gt;Pol&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;ite [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property DateinameEmpfaenger() As String
            Get
                Return ResourceManager.GetString("DateinameEmpfaenger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandant&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandantin&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Geschädigter&lt;/label&gt;
        '''    &lt;value&gt;Gesch&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Geschädigte&lt;/label&gt;
        '''    &lt;value&gt;Gesch&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Rechtsanwalt&lt;/label&gt;
        '''    &lt;value&gt;RA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Polizei&lt;/label&gt;
        '''    &lt;value&gt;Pol&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;ite [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property PostAbsender() As String
            Get
                Return ResourceManager.GetString("PostAbsender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Schreiben&lt;/label&gt;
        '''    &lt;value&gt;Schreiben&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Email&lt;/label&gt;
        '''    &lt;value&gt;Email&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Fax&lt;/label&gt;
        '''    &lt;value&gt;Fax&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;beA&lt;/label&gt;
        '''    &lt;value&gt;beA&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Antrag&lt;/label&gt;
        '''    &lt;value&gt;Antrag&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Verteidigungsschrift&lt;/label&gt;
        '''    &lt;value&gt;VertSchr&lt;/value&gt;
        '''  &lt;/item&gt;
        '''&lt;/lis [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property PostBezeichnungen() As String
            Get
                Return ResourceManager.GetString("PostBezeichnungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Rechnung&lt;/label&gt;
        '''    &lt;value&gt;Rng&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Gebührenberechnung&lt;/label&gt;
        '''    &lt;value&gt;GBer&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Kostenfestsetzungsantrag&lt;/label&gt;
        '''    &lt;value&gt;Kfa&lt;/value&gt;
        '''  &lt;/item&gt;
        '''&lt;/list&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property RechnungBezeichnungen() As String
            Get
                Return ResourceManager.GetString("RechnungBezeichnungen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandant&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Mandantin&lt;/label&gt;
        '''    &lt;value&gt;Mdt&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Rechtsschutzversicherung&lt;/label&gt;
        '''    &lt;value&gt;RS&lt;/value&gt;
        '''  &lt;/item&gt;
        '''&lt;/list&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property RechnungEmpfaenger() As String
            Get
                Return ResourceManager.GetString("RechnungEmpfaenger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;list&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Vermerk&lt;/label&gt;
        '''    &lt;value&gt;Verm&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Aktenvermerk&lt;/label&gt;
        '''    &lt;value&gt;AVerm&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Telefonvermerk&lt;/label&gt;
        '''    &lt;value&gt;TelVerm&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Telefonnotiz&lt;/label&gt;
        '''    &lt;value&gt;TelNot&lt;/value&gt;
        '''  &lt;/item&gt;
        '''  &lt;item&gt;
        '''    &lt;label&gt;Verfügung&lt;/label&gt;
        '''    &lt;value&gt;Vfg&lt;/value&gt;
        '''  &lt;/item&gt;
        '''&lt;/list&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property VermerkBezeichnungen() As String
            Get
                Return ResourceManager.GetString("VermerkBezeichnungen", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
